"""initial schema

Revision ID: f8933725c180
Revises: 
Create Date: 2026-03-09 13:11:30.165103

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f8933725c180'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
